apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coit-frontend-deployment.yaml
- ./service-coit-frontend-lb.yaml
images:
- name: coitlearning/coit-frontend
  newTag: latest

namePrefix: Frontend-
nameSuffix: -development

commonLabels:
  customer: customer1
  environment: development
  myapp: coit-frontend
  app: coitfrontend

labels:
  - pairs:
      location: us-west
